
edge_config:
  bootstrap: https://apigee.net/edgemicro/bootstrap/organization/org/environment/env...
  jwt_public_key: http://apigee.net/edgemicro/publicKey...
  managementUri: https://api.enterprise.apigee.com
  vaultName: microgateway
  authUri: https://%s-%s.apigee.net/edgemicro-auth
  baseUri: https://edgemicroservices.apigee.net/edgemicro/%s/organization/%s/environment/%s
  bootstrapMessage: Please copy the following property to the edge micro agent config
  keySecretMessage: The following credentials are required to start edge micro

edgemicro:
  port: 8000
  max_connections: 1000
  config_change_poll_interval: 600
  logging:
    level: error
    dir: /var/tmp
    stats_log_interval: 60
    rotate_interval: 24
  plugins:
    sequence:
      - oauth

headers:
  x-forwarded-for: true
  x-forwarded-host: true
  x-request-id: true
  x-response-time: true
  via: true

oauth:
  allowNoAuthorization: false
  allowInvalidAuthorization: false
